package view;

import controller.ControllerSelect;
import tools.ListArm;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class Home extends JFrame {
    private JTextField txtSeach;
    private JButton btnSearch;
    private JTable tbNames;
    private JPanel panel;
    private JScrollPane paneMain;
    private JPanel panelFields;
    private JPanel fildPanelPri;
    private JPanel fildPanelSeg;
    private JPanel panelSegTable;

    public Home() {

        $$$setupUI$$$();
        try {

            this.setTitle("COOKBOOK");

            this.setContentPane(panel);

            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            this.setLocationRelativeTo(null);

            this.setSize(400, 400);


            btnSearch.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {

                    reshTabel();
                }
            });
        } catch (Exception vl) {

            System.out.println("Home erro: " + vl);

        }

    }

    private void reshTabel() {
        List<ListArm> listRecives = null;

        ControllerSelect ever = new ControllerSelect();

        listRecives = ever.selectEver();

        DefaultTableModel tmp = (DefaultTableModel) tbNames.getModel();

        try {
            for (int i = 0; i < listRecives.size(); i++) {
                tmp.addRow(new Object[]{
                        listRecives.get(i).getNomeRecive(),
                        listRecives.get(i).getId()
                });
            }
        } catch (Exception e) {
            System.out.println(e);
        }


    }

    public JTable getTbNames() {
        return this.tbNames;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        try {

            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("Name");

            modelo.addColumn("Id");

            this.paneMain = new JScrollPane();

            this.tbNames = new JTable();

            this.tbNames.setModel(modelo);

            this.paneMain.setViewportView(tbNames);

        } catch (Exception ct) {
            System.out.println("Erro em Create UI: " + ct);
        }


    }

    public static void main(String[] args) {

        try {
            Home sreen = new Home();

            sreen.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panelFields = new JPanel();
        panelFields.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(panelFields, gbc);
        fildPanelPri = new JPanel();
        fildPanelPri.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelFields.add(fildPanelPri, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        txtSeach = new JTextField();
        fildPanelPri.add(txtSeach, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        fildPanelSeg = new JPanel();
        fildPanelSeg.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelFields.add(fildPanelSeg, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnSearch = new JButton();
        btnSearch.setText("Button");
        fildPanelSeg.add(btnSearch, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelSegTable = new JPanel();
        panelSegTable.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(panelSegTable, gbc);
        panelSegTable.add(paneMain, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        paneMain.setViewportView(tbNames);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
